# Generated by Django 4.2.16 on 2024-10-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=100)),
                ('recipe_descirpiton', models.CharField(max_length=1000)),
                ('recipe_image', models.ImageField(upload_to='recipe_images/')),
            ],
        ),
    ]
