# Generated by Django 4.2.16 on 2024-10-10 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_descirpiton',
            new_name='recipe_desciption',
        ),
    ]
