# Generated by Django 4.2.16 on 2024-10-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_rename_recipe_descirpiton_recipe_recipe_desciption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_desciption',
            field=models.CharField(max_length=100000),
        ),
    ]
