# Generated by Django 4.2.16 on 2024-10-10 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_recipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
